### ISSUE TITLE
Error when creating Light

### ISSUE THREAD

**Issue by gmf1111** [leomoon-studios/blender-light-studio#4]
I am getting the following error when trying to create a light:

Traceback (most recent call last):
  File "/Users/GMF/Library/Application Support/Blender/2.75/scripts/addons/blender-light-studio/light_operators.py", line 141, in execute
    new_objects = (A ^ B).pop().objects
KeyError: 'pop from an empty set'

location: <unknown location>:-1

Your recent update fixed the following error on creating the Light Studio:

Traceback (most recent call last):
File "/Users/GMF/Library/Application Support/Blender/2.75/scripts/addons/blender-light-studio/light_operators.py", line 60, in execute
cpanel = [ob for ob in bpy.context.scene.objects if ob.name.startswith('BLS_PANEL')][0]
IndexError: list index out of range

location: <unknown location>:-1

I am currently on OS X Yosemite.

Thanks for the hard work and a great addon!

**Comment by theres1** [comment]
Thx, fixed in v1.2.3
