### ISSUE TITLE
Blender 3.5 on macOS Issue

### ISSUE THREAD

**Issue by leomoon** [leomoon-studios/blender-light-studio#73]
LightStudio can't be activated on macOS using Blender 3.5.1:
```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/rebecca/Library/Application Support/Blender/3.5/scripts/addons/leomoon-lightstudio-master/__init__.py", line 21, in <module>
    auto_load.init()
  File "/Users/rebecca/Library/Application Support/Blender/3.5/scripts/addons/leomoon-lightstudio-master/auto_load.py", line 30, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/Users/rebecca/Library/Application Support/Blender/3.5/scripts/addons/leomoon-lightstudio-master/auto_load.py", line 67, in get_all_submodules
    return list(iter_submodules(directory, [directory.name](http://directory.name/)))
  File "/Users/rebecca/Library/Application Support/Blender/3.5/scripts/addons/leomoon-lightstudio-master/auto_load.py", line 74, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/Applications/Blender.app/Contents/Resources/3.5/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/rebecca/Library/Application Support/Blender/3.5/scripts/addons/leomoon-lightstudio-master/deleteOperator.py", line 4, in <module>
    from . import light_list
  File "/Users/rebecca/Library/Application Support/Blender/3.5/scripts/addons/leomoon-lightstudio-master/light_list.py", line 6, in <module>
    from . operators import modal
  File "/Users/rebecca/Library/Application Support/Blender/3.5/scripts/addons/leomoon-lightstudio-master/operators/modal.py", line 5, in <module>
    from . modal_utils import *
  File "/Users/rebecca/Library/Application Support/Blender/3.5/scripts/addons/leomoon-lightstudio-master/operators/modal_utils.py", line 183, in <module>
    lightIconShader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details
```

**Comment by teddylindsey** [comment]
Sounds like cross-platform shader generation needs to use the new gpu API that supports Mac/Metal.

**Comment by leomoon** [comment]
more info:
https://www.projects.blender.org/blender/blender/issues/107332

need to use new GPU API:
https://docs.blender.org/api/current/gpu.html#triangle-with-custom-shader

**Comment by dusticelli** [comment]
What should be done to fix the problem?

this file should be pasted to the text-editor and executed, like descirbed?
https://docs.blender.org/api/current/gpu.html#triangle-with-custom-shader

That doesn't change anything for me. It is still not possible to activate LightStudio on a Mac and Blender 3.5.1. I would love to use it on the latest stable blender version. Will this issue be fixed in a future release?

**Comment by leomoon** [comment]
We are working on a fix to support Metal on macOS but by changing GPU Backend from Metal to OpenGL you can use LightStudio on macOS until we have a fix.

- Open Blender
- Go to `Edit` > `Preferences` > `System`
- Change `GPU Backend` to `OpenGL`
- Close Blender
- Open Blender and install LightStudio

**Comment by leomoon** [comment]
This is fixed in the new version.
