### ISSUE TITLE
LightStudio can't be activated on blender4.0

### ISSUE THREAD

**Issue by optdesigns** [leomoon-studios/blender-light-studio#75]
LightStudio can't be activated on blender4.0

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\__init__.py", line 21, in <module>
    auto_load.init()
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\auto_load.py", line 30, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\auto_load.py", line 67, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\auto_load.py", line 74, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\deleteOperator.py", line 4, in <module>
    from . import light_list
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\light_list.py", line 6, in <module>
    from . operators import modal
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\operators\modal.py", line 5, in <module>
    from . modal_utils import *
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\operators\modal_utils.py", line 10, in <module>
    shader2Dcolor = gpu.shader.from_builtin('2D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_UNIFORM_COLOR'


```

**Comment by Owiilnice** [comment]
Me too, 4.0 is not available at the moment

**Comment by Shure79** [comment]
The same here with the same errors.

**Comment by mjjhjk** [comment]
+1

**Comment by leomoon** [comment]
We are working on a fix.

**Comment by Prototype-Zer0** [comment]
I have opened a PR for a quick hotfix until a new release is dropped by the studio: https://github.com/leomoon-studios/leomoon-lightstudio/pull/76
In the meantime can someone pull my changes and check for anything that I might have missed? I know the developers are super busy so I'm gonna try to help to make this work for everyone.
##
UPDATE: Looks like the devs fixed it and now it's better than ever.

**Comment by leomoon** [comment]
Fixed in the newest version.
