### ISSUE TITLE
I'm getting the following error: LLS_OT_control_panel has been removed

### ISSUE THREAD

**Issue by matteo-dirollo** [leomoon-studios/blender-light-studio#79]
Traceback (most recent call last):
  File "C:\Users\Matteo Di Rollo\Softwares\Blender\stable\blender-4.0.0+stable.878f71061b8e\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\__init__.py", line 38, in register
    deleteOperator.add_shortkeys()
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\deleteOperator.py", line 95, in add_shortkeys
    register_keymaps()
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\deleteOperator.py", line 71, in register_keymaps
    km, kmis =  get_user_keymap_item('Object Mode', 'object.delete', multiple_entries=True)
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\common.py", line 12, in get_user_keymap_item
    return km, [i[1] for i in km.keymap_items.items() if i[0] == keymap_item_idname]
AttributeError: 'NoneType' object has no attribute 'keymap_items'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\checksqe.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\draw.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\exception.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\kitsu.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\log.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\operators.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\ops.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\opsdata.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\prefs.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\props.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\ui.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Matteo Di Rollo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\vars.py'
Exception in module register(): C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\__init__.py
Traceback (most recent call last):
  File "C:\Users\Matteo Di Rollo\Softwares\Blender\stable\blender-4.0.0+stable.878f71061b8e\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\__init__.py", line 33, in register
    auto_load.register()
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\auto_load.py", line 38, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'LLS_PT_Studio'
blenderkit updater: Running background check for update
blenderkit addon: Starting background checking thread
blenderkit addon: Checking for update now in background
blenderkit addon: Checking for update function
blenderkit INFO: Global dir permissions are OK. [11:37:46.891, utils.py:1281]
blenderkit addon: Read in JSON settings from file
blenderkit addon: Determined it's not yet time to check for updates
blenderkit addon: Aborting check for updated, check interval not reached
blenderkit addon: Finished check update, doing callback
blenderkit addon: Running background update callback
blenderkit addon: BG thread: Finished check update, no callback
blenderkit INFO: Dependencies are available [11:37:47.167, dependencies.py:111]
blenderkit INFO: Daemon is running on port 62485! [11:37:48.769, timer.py:87]
Traceback (most recent call last):
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Realtime_Materials\t3dn_bip\threads.py", line 66, in _emplace_timer
    preview.icon_size = data['icon_size']
TypeError: 'NoneType' object is not subscriptable
Keymaps not read.
Read blend: "C:\Users\Matteo Di Rollo\Desktop\Share\JeamsRead_cosmetic\JamesRead_GradualTan_v8.blend"
WARN (bke.modifier): C:\Users\blender\git\blender-v400\blender.git\source\blender\blenkernel\intern\modifier.cc:461 BKE_modifier_set_error: Object: "Cylinder_cup", Modifier: "WeightedNormal", Enable 'Auto Smooth' in Object Data Properties
WARN (bke.modifier): C:\Users\blender\git\blender-v400\blender.git\source\blender\blenkernel\intern\modifier.cc:461 BKE_modifier_set_error: Object: "Bottle", Modifier: "WeightedNormal", Enable 'Auto Smooth' in Object Data Properties
Traceback (most recent call last):
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\operators\modal.py", line 415, in invoke
    panel_global = Panel(Vector((15, 45)), pw, pw*(9/16))
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\operators\modal_utils.py", line 340, in __init__
    self.button_fast_3d_edit = Button(Vector((0,0)), f'Light Brush [{kmi.type}]')
AttributeError: 'NoneType' object has no attribute 'type'
Error: Python: Traceback (most recent call last):
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\operators\modal.py", line 415, in invoke
    panel_global = Panel(Vector((15, 45)), pw, pw*(9/16))
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\operators\modal_utils.py", line 340, in __init__
    self.button_fast_3d_edit = Button(Vector((0,0)), f'Light Brush [{kmi.type}]')
AttributeError: 'NoneType' object has no attribute 'type'

Traceback (most recent call last):
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\operators\modal.py", line 493, in modal
    update_light_sets(self.panel, context)
  File "C:\Users\Matteo Di Rollo\Softwares\Blender\stable\blender-4.0.0+stable.878f71061b8e\4.0\scripts\modules\bpy_types.py", line 898, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type LLS_OT_control_panel has been removed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matteo Di Rollo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\operators\modal.py", line 673, in modal
    self._unregister_handler()
  File "C:\Users\Matteo Di Rollo\Softwares\Blender\stable\blender-4.0.0+stable.878f71061b8e\4.0\scripts\modules\bpy_types.py", line 898, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type LLS_OT_control_panel has been removed

**Comment by leomoon** [comment]
this should be fixed in LightStudio 2.15.1.

Please make sure the old LightStudio version is removed.
